
import DAO.TipoCategoriaDAO;
import DAO.TipoDAO;
import DTO.TipoCategoriaDTO;
import DTO.TipoDTO;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bena
 */
public class Tipos extends javax.swing.JFrame {

    /**
     * Creates new form Tipos
     */
    public Tipos() throws SQLException {
        initComponents();
        loadTableTipos();
        loadCmbTipoCategoria();
    }
    public void loadTableTipos() throws SQLException{
        TipoDAO tipo = new TipoDAO();
        List<TipoDTO> listaTipos = tipo.getAllWithCat();
        DefaultTableModel model = (DefaultTableModel) tableTipo.getModel();   
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        for (TipoDTO item : listaTipos) {
            System.out.println(item.getCodTipo());
            System.out.println(item.getNombre());
            Object[] row = { item.getCodTipo(), item.getNombre(), item.getCategoria().getCodTipoCat() };
            model.addRow(row);
            
        }
    }
    public void loadCmbTipoCategoria() throws SQLException{
        TipoCategoriaDAO categoria = new TipoCategoriaDAO();
        List<TipoCategoriaDTO> listaTipos = categoria.getAll();
        cmbTipoCategoria.removeAllItems();
        for (TipoCategoriaDTO item : listaTipos) {
            cmbTipoCategoria.addItem(item.getCodTipoCat());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreTipo = new javax.swing.JLabel();
        lblCodTipo = new javax.swing.JLabel();
        txtNombreTipo = new javax.swing.JTextField();
        txtCodigoTipo = new javax.swing.JTextField();
        btnAgregarTipo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTipo = new javax.swing.JTable();
        btnEliminarTipo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        lblTipoCategoria = new javax.swing.JLabel();
        cmbTipoCategoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombreTipo.setText("Nombre");

        lblCodTipo.setText("Codigo de Tipo");

        btnAgregarTipo.setText("Agregar");
        btnAgregarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTipoActionPerformed(evt);
            }
        });

        tableTipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cod. Categoria"
            }
        ));
        jScrollPane2.setViewportView(tableTipo);

        btnEliminarTipo.setText("Eliminar");
        btnEliminarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTipoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        lblTipoCategoria.setText("Categoria");

        cmbTipoCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCodTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNombreTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTipoCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipoCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarTipo)
                    .addComponent(btnEliminarTipo))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreTipo)
                    .addComponent(lblCodTipo)
                    .addComponent(txtCodigoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoCategoria)
                    .addComponent(cmbTipoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregarTipo)
                        .addGap(35, 35, 35)
                        .addComponent(btnEditar)
                        .addGap(36, 36, 36)
                        .addComponent(btnEliminarTipo)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTipoActionPerformed
        TipoDAO tipo = new TipoDAO();
        String nombre = txtNombreTipo.getText();
        String codTipo = txtCodigoTipo.getText();
        String codTipoCat = cmbTipoCategoria.getModel().getSelectedItem().toString();
        
        boolean validNom = true;
        boolean validCod = true;
        if(codTipo.length()< 3){
            JOptionPane.showMessageDialog(null, "el codigo debe tener al menos 3 caracters");
            validCod = false;
        }
        else{
        }
        if(nombre.length()< 5){
            JOptionPane.showMessageDialog(null, "el nombre debe tener al menos 5 caracters");
            validNom = false;
        }
        
        if(validNom && validCod){
            TipoCategoriaDAO categoriaSearch = new TipoCategoriaDAO();
            TipoCategoriaDTO categoria = new TipoCategoriaDTO();
            
            try {
                categoria = categoriaSearch.getByCode(codTipoCat);
                boolean insertionResult = false;
                try {
                    insertionResult = tipo.add(codTipo, nombre, categoria.getId() );
                } catch (SQLException ex) {
                    Logger.getLogger(Tipos.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println(insertionResult);
                if(insertionResult){
                    try {
                        this.loadTableTipos();
                    } catch (SQLException ex) {
                        Logger.getLogger(Tipos.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JOptionPane.showMessageDialog(null, "Tipo agregado con exito!");
                    System.out.println("Tipo agregado con exito!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Tipos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_btnAgregarTipoActionPerformed

    private void btnEliminarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTipoActionPerformed
        // TODO add your handling code here:
        int selected_row = tableTipo.getSelectedRow();
        if (selected_row != -1){
            String codTipo = tableTipo.getModel().getValueAt(selected_row, 0).toString();
            TipoDAO tipo = new TipoDAO();
            try {
                boolean result = tipo.disabledByCodTipo(codTipo);
                if (result){
                    JOptionPane.showMessageDialog(null, "Tipo eliminado con exito!");
                    loadTableTipos();
                }
            } catch (SQLException ex) {
                Logger.getLogger(Tipos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEliminarTipoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int selected_row = tableTipo.getSelectedRow();
        System.out.println(tableTipo.getModel().getValueAt(selected_row, 2).toString());
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Tipos().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Tipos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarTipo;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminarTipo;
    private javax.swing.JComboBox<String> cmbTipoCategoria;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCodTipo;
    private javax.swing.JLabel lblNombreTipo;
    private javax.swing.JLabel lblTipoCategoria;
    private javax.swing.JTable tableTipo;
    private javax.swing.JTextField txtCodigoTipo;
    private javax.swing.JTextField txtNombreTipo;
    // End of variables declaration//GEN-END:variables
}



